#!/bin/bash
echo "================================"
echo "LOTTERY ANALYSIS SYSTEM DEMO"
echo "================================"
echo ""
echo "1. Database Statistics"
echo "----------------------"
python main.py --stats --lottery lotofacil 2>&1 | grep -A 5 "DATABASE STATISTICS"
echo ""
echo "2. Generate 3 Games (Balanced Strategy)"
echo "----------------------------------------"
python main.py --generate-games --lottery lotofacil --count 3 --strategy balanced 2>&1 | tail -20
echo ""
echo "3. Quick Analysis"
echo "-----------------"
python main.py --analyze --lottery lotofacil 2>&1 | grep -A 15 "TOP 10 MOST FREQUENT"
echo ""
echo "================================"
echo "Demo Complete!"
echo "================================"
